package com.dev.openai.travelassistant.config;

import java.util.LinkedHashMap;
import java.util.Map;

public class InMemoryDB {

    public static Map<String, String> getMap() {
        final LinkedHashMap<String, String> citiesAndCountries = new LinkedHashMap<String, String>() {{
            put("Hyderabad", "India");
            put("Pune", "India");
            put("Delhi", "India");
            put("Otty", "India");
            put("Madhuri", "India");
            put("Mysore", "India");
            put("Amritsar", "India");
            put("Jaisalmer", "India");
            put("Udaipur", "India");
            put("Chennai", "India");
            put("Kochi", "India");
            put("Varanasi", "India");
            put("Kolkata", "India");
            put("Bangalore", "India");
            put("Agra", "India");
            put("Mumbai", "India");
            put("Jaipur", "India");
            put("Hyderabad", "India");
            put("Pune", "India");
            put("Delhi", "India");
            put("Otty", "India");
            put("Madhuri", "India");
            put("Mysore", "India");
            put("Amritsar", "India");
            put("Jaisalmer", "India");
            put("Udaipur", "India");
            put("Chennai", "India");
            put("Kochi", "India");
            put("Varanasi", "India");
            put("Kolkata", "India");
            put("Bangalore", "India");
            put("Agra", "India");
            put("Mumbai", "India");
            put("Jaipur", "India");
            put("Paris", "France");
            put("Marseille", "France");
            put("Lyon", "France");
            put("Bordeaux", "France");
            put("Strasbourg", "France");
            put("Annecy", "France");
            put("Metz", "France");
            put("Reims", "France");
            put("Colmar", "France");
            put("Nice", "France");
            put("Toulouse", "France");
            put("Chamonix", "France");
            put("Lille", "France");
            put("Chicago", "Illinois");
            put("New Orleans", "Louisiana");
            put("Seattle", "Washington");
            put("San Diego", "California");
            put("San Francisco", "California");
            put("Miami", "Florida");
            put("Washington", "DC");
            put("New York City", "New York");
            put("Portland", "Oregon");
            put("Boston", "Massachusetts");
            put("Philadelphia", "Pennsylvania");
            put("Austin", "Texas");
            put("Charleston", "South Carolina");
            put("Maui", "Hawaii");
            put("Monterey", "California");
            put("Niagara Falls", "New York");
            put("Sedona", "Arizona");
            put("Anchorage", "Alaska");
            put("Nantucket", "Massachusetts");
            put("Rome", "Italy");
            put("Porto", "Portugal");
            put("Dublin", "Ireland");
            put("Vienna", "Austria");
            put("Salzburg", "Austria");
            put("Munich", "Germany");
            put("Rothenberg ob der Tauber", "Germany");
            put("Athens", "Greece");
            put("Stockholm", "Sweden");
            put("Madrid", "Spain");
            put("Budapest", "Hungary");
            put("Prague", "Czech Republic");
            put("Amsterdam", "Netherlands");
            put("Venice", "Italy");
            put("Florence", "Italy");
            put("Copenhagen", "Denmark");
            put("Barcelona", "Spain (Catalonia)");
            put("Split", "Croatia");
            put("Berlin", "Germany");
            put("New York City", "United States");
            put("Mexico City", "Mexico");
            put("Guadalajara", "Mexico");
            put("Monterrey", "Mexico");
            put("Puebla", "Mexico");
            put("Tijuana", "Mexico");
            put("Cancun", "Mexico");
            put("Leon", "Mexico");
            put("Juarez", "Mexico");
            put("Merida", "Mexico");
            put("Chihuahua", "Mexico");
            put("Los Angeles", "United States");
            put("Chicago", "United States");
            put("San Francisco", "United States");
            put("Miami", "United States");
            put("Las Vegas", "United States");
            put("Boston", "United States");
            put("Washington, D.C.", "United States");
            put("Seattle", "United States");
            put("Atlanta", "United States");
            put("Toronto", "Canada");
            put("Vancouver", "Canada");
            put("Montreal", "Canada");
            put("Calgary", "Canada");
            put("Ottawa", "Canada");
            put("Edmonton", "Canada");
            put("Quebec City", "Canada");
            put("Winnipeg", "Canada");
            put("Halifax", "Canada");
            put("Victoria", "Canada");
            put("London", "United Kingdom");
            put("Manchester", "United Kingdom");
            put("Birmingham", "United Kingdom");
            put("Liverpool", "United Kingdom");
            put("Glasgow", "United Kingdom");
            put("Edinburgh", "United Kingdom");
            put("Bristol", "United Kingdom");
            put("Leeds", "United Kingdom");
            put("Newcastle", "United Kingdom");
            put("Sheffield", "United Kingdom");
            put("Marseille", "United Kingdom");
            put("Lyon", "United Kingdom");
            put("Toulouse", "United Kingdom");
            put("Nice", "United Kingdom");
            put("Bordeaux", "United Kingdom");
            put("Lille", "United Kingdom");
            put("Strasbourg", "United Kingdom");
            put("Nantes", "United Kingdom");
            put("Montpellier", "United Kingdom");
            put("Berlin", "Germany");
            put("Munich", "Germany");
            put("Hamburg", "Germany");
            put("Frankfurt", "Germany");
            put("Cologne", "Germany");
            put("Stuttgart", "Germany");
            put("Dusseldorf", "Germany");
            put("Leipzig", "Germany");
            put("Dresden", "Germany");
            put("Nuremberg", "Germany");
            put("Madrid", "Spain");
            put("Barcelona", "Spain");
            put("Valencia", "Spain");
            put("Seville", "Spain");
            put("Zaragoza", "Spain");
            put("Malaga", "Spain");
            put("Murcia", "Spain");
            put("Palma de Mallorca", "Spain");
            put("Bilbao", "Spain");
            put("Alicante", "Spain");
            put("Sydney", "Australia");
            put("Melbourne", "Australia");
            put("Brisbane", "Australia");
            put("Perth", "Australia");
            put("Adelaide", "Australia");
            put("Gold Coast", "Australia");
            put("Canberra", "Australia");
            put("Newcastle", "Australia");
            put("Hobart", "Australia");
            put("Darwin", "Australia");
            put("Tokyo", "Japan");
            put("Osaka", "Japan");
            put("Kyoto", "Japan");
            put("Hiroshima", "Japan");
            put("Nagoya", "Japan");
            put("Sapporo", "Japan");
            put("Fukuoka", "Japan");
            put("Kobe", "Japan");
            put("Yokohama", "Japan");
            put("Okinawa", "Japan");
            put("Beijing", "China");
            put("Shanghai", "China");
            put("Guangzhou", "China");
            put("Shenzhen", "China");
            put("Hangzhou", "China");
            put("Chengdu", "China");
            put("Xi'an", "China");
            put("Nanjing", "China");
            put("Wuhan", "China");
            put("Chongqing", "China");
            put("Rio de Janeiro", "Brazil");
            put("Sao Paulo", "Brazil");
            put("Brasilia", "Brazil");
            put("Salvador", "Brazil");
            put("Fortaleza", "Brazil");
            put("Belo Horizonte", "Brazil");
            put("Manaus", "Brazil");
            put("Recife", "Brazil");
            put("Curitiba", "Brazil");
            put("Porto Alegre", "Brazil");
            put("Seoul", "South Korea");
            put("Busan", "South Korea");
            put("Incheon", "South Korea");
            put("Daegu", "South Korea");
            put("Daejeon", "South Korea");
            put("Gwangju", "South Korea");
            put("Ulsan", "South Korea");
            put("Suwon", "South Korea");
            put("Changwon", "South Korea");
            put("Seongnam", "South Korea");
            put("Moscow", "Russia");
            put("Saint Petersburg", "Russia");
            put("Novosibirsk", "Russia");
            put("Yekaterinburg", "Russia");
            put("Kazan", "Russia");
            put("Nizhny Novgorod", "Russia");
            put("Chelyabinsk", "Russia");
            put("Samara", "Russia");
            put("Omsk", "Russia");
            put("Rostov-on-Don", "Russia");
            put("Jakarta", "Indonesia");
            put("Surabaya", "Indonesia");
            put("Bandung", "Indonesia");
            put("Medan", "Indonesia");
            put("Semarang", "Indonesia");
            put("Bekasi", "Indonesia");
            put("Palembang", "Indonesia");
            put("Tangerang", "Indonesia");
            put("Makassar", "Indonesia");
            put("South Tangerang", "Indonesia");
            put("Karachi", "Pakistan");
            put("Lahore", "Pakistan");
            put("Faisalabad", "Pakistan");
            put("Rawalpindi", "Pakistan");
            put("Multan", "Pakistan");
            put("Islamabad", "Pakistan");
            put("Peshawar", "Pakistan");
            put("Quetta", "Pakistan");
            put("Sialkot", "Pakistan");
            put("Bahawalpur", "Pakistan");
            put("Lagos", "Nigeria");
            put("Kano", "Nigeria");
            put("Ibadan", "Nigeria");
            put("Kaduna", "Nigeria");
            put("Port Harcourt", "Nigeria");
            put("Benin City", "Nigeria");
            put("Maiduguri", "Nigeria");
            put("Zaria", "Nigeria");
            put("Aba", "Nigeria");
            put("Jos", "Nigeria");
            put("Dhaka", "Bangladesh");
            put("Chittagong", "Bangladesh");
            put("Khulna", "Bangladesh");
            put("Rajshahi", "Bangladesh");
            put("Comilla", "Bangladesh");
            put("Sylhet", "Bangladesh");
            put("Barisal", "Bangladesh");
            put("Rangpur", "Bangladesh");
            put("Narayanganj", "Bangladesh");
            put("Gazipur", "Bangladesh");
            put("Manila", "Philippines");
            put("Quezon City", "Philippines");
            put("Caloocan", "Philippines");
            put("Davao City", "Philippines");
            put("Cebu City", "Philippines");
            put("Zamboanga City", "Philippines");
            put("Antipolo", "Philippines");
            put("Pasig", "Philippines");
            put("Taguig", "Philippines");
            put("Cagayan de Oro", "Philippines");
            put("Cairo", "Egypt");
            put("Alexandria", "Egypt");
            put("Giza", "Egypt");
            put("Shubra El Kheima", "Egypt");
            put("Port Said", "Egypt");
            put("Suez", "Egypt");
            put("Luxor", "Egypt");
            put("Aswan", "Egypt");
            put("Damietta", "Egypt");
            put("Mansoura", "Egypt");
            put("Ho Chi Minh City", "Vietnam");
            put("Hanoi", "Vietnam");
            put("Hai Phong", "Vietnam");
            put("Can Tho", "Vietnam");
            put("Da Nang", "Vietnam");
            put("Bien Hoa", "Vietnam");
            put("Hue", "Vietnam");
            put("Nha Trang", "Vietnam");
            put("Vinh", "Vietnam");
            put("Qui Nhon", "Vietnam");
            put("Tehran", "Iran");
            put("Mashhad", "Iran");
            put("Isfahan", "Iran");
            put("Karaj", "Iran");
            put("Shiraz", "Iran");
            put("Tabriz", "Iran");
            put("Qom", "Iran");
            put("Ahvaz", "Iran");
            put("Kermanshah", "Iran");
            put("Urmia", "Iran");
            put("Istanbul", "Turkey");
            put("Ankara", "Turkey");
            put("Izmir", "Turkey");
            put("Bursa", "Turkey");
            put("Adana", "Turkey");
            put("Gaziantep", "Turkey");
            put("Konya", "Turkey");
            put("Antalya", "Turkey");
            put("Kayseri", "Turkey");
            put("Mersin", "Turkey");
            put("Bangkok", "Thailand");
            put("Nonthaburi", "Thailand");
            put("Nakhon Ratchasima", "Thailand");
            put("Chiang Mai", "Thailand");
            put("Hat Yai", "Thailand");
            put("Udon Thani", "Thailand");
            put("Pak Kret", "Thailand");
            put("Khon Kaen", "Thailand");
            put("Nakhon Si Thammarat", "Thailand");
            put("Chaophraya Surasak", "Thailand");
            put("Yangon", "Myanmar");
            put("Mandalay", "Myanmar");
            put("Naypyidaw", "Myanmar");
            put("Mawlamyine", "Myanmar");
            put("Bago", "Myanmar");
            put("Pathein", "Myanmar");
            put("Monywa", "Myanmar");
            put("Sittwe", "Myanmar");
            put("Meiktila", "Myanmar");
            put("Taunggyi", "Myanmar");
            put("Johannesburg", "South Africa");
            put("Cape Town", "South Africa");
            put("Durban", "South Africa");
            put("Pretoria", "South Africa");
            put("Port Elizabeth", "South Africa");
            put("Bloemfontein", "South Africa");
            put("Polokwane", "South Africa");
            put("Nelspruit", "South Africa");
            put("Kimberley", "South Africa");
            put("East London", "South Africa");
            put("Bogotá", "Colombia");
            put("Medellín", "Colombia");
            put("Cali", "Colombia");
            put("Barranquilla", "Colombia");
            put("Cartagena", "Colombia");
            put("Cúcuta", "Colombia");
            put("Bucaramanga", "Colombia");
            put("Ibagué", "Colombia");
            put("Soledad", "Colombia");
            put("Pereira", "Colombia");
        }};
        return citiesAndCountries;
    }
}

